"""deleted redundant colour table, changed match colour ids to values

Revision ID: 512d1b93e16f
Revises: 
Create Date: 2025-05-13 11:29:33.327414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '512d1b93e16f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('correct_matches', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('friendships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('correct_colour', sa.String(length=20), nullable=False),
    sa.Column('selected_colour', sa.String(length=20), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('euclidean_distance', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_results')
    op.drop_table('friendships')
    op.drop_table('users')
    # ### end Alembic commands ###
