"""Renamed any colours to color

Revision ID: 5ef006ed9cad
Revises: fe13af0ca509
Create Date: 2025-05-15 18:13:47.850381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ef006ed9cad'
down_revision = 'fe13af0ca509'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_results', schema=None) as batch_op:
        batch_op.alter_column('selected_colour', new_column_name='selected_color')
        batch_op.alter_column('correct_colour', new_column_name='correct_color')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_results', schema=None) as batch_op:
        batch_op.alter_column('selected_color', new_column_name='selected_colour')
        batch_op.alter_column('correct_color', new_column_name='correct_colour')

    # ### end Alembic commands ###
