"""Initial database

Revision ID: 743a70fe3bff
Revises: 
Create Date: 2025-05-13 11:47:44.460805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '743a70fe3bff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colours',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rgb_val', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('correct_matches', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('friendships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['users.id'], name ="fk_friendships_friend_id_users"),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name ="fk_friendships_user_id_users"),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('correct_colour_id', sa.Integer(), nullable=False),
    sa.Column('selected_colour_id', sa.Integer(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('euclidean_distance', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['correct_colour_id'], ['colours.id'], name ="fk_game_results_correct_colour_id_colours"),
    sa.ForeignKeyConstraint(['selected_colour_id'], ['colours.id'], name ="fk_game_results_selected_colour_id_colours"),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name ="fk_game_results_user_id_users"),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_results')
    op.drop_table('friendships')
    op.drop_table('users')
    op.drop_table('colours')
    # ### end Alembic commands ###
