"""deleted redundant colour table, changed match colour ids to values

Revision ID: a33bd767d704
Revises: c72597704a99
Create Date: 2025-05-13 10:52:43.759752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a33bd767d704'
down_revision = 'c72597704a99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('colours')
    with op.batch_alter_table('game_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correct_colour', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('selected_colour', sa.String(length=20), nullable=False))
        batch_op.drop_column('correct_colour_id')
        batch_op.drop_column('selected_colour_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_colour_id', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('correct_colour_id', sa.VARCHAR(length=20), nullable=False))
        batch_op.drop_column('selected_colour')
        batch_op.drop_column('correct_colour')

    op.create_table('colours',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('rgb_val', sa.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
