"""Altered the GameResult table 

Revision ID: aa07aa9f1456
Revises: 743a70fe3bff
Create Date: 2025-05-13 11:50:07.327110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa07aa9f1456'
down_revision = '743a70fe3bff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correct_colour', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('selected_colour', sa.String(length=20), nullable=False))
        batch_op.drop_constraint('fk_game_results_correct_colour_id_colours', type_='foreignkey')
        batch_op.drop_constraint('fk_game_results_selected_colour_id_colours', type_='foreignkey')
        batch_op.drop_column('correct_colour_id')
        batch_op.drop_column('selected_colour_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_colour_id', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('correct_colour_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_game_results_selected_colour_id_colours', 'colours', ['selected_colour_id'], ['id'])
        batch_op.create_foreign_key('fk_game_results_correct_colour_id_colours', 'colours', ['correct_colour_id'], ['id'])
        batch_op.drop_column('selected_colour')
        batch_op.drop_column('correct_colour')

    # ### end Alembic commands ###
