"""Revomved the colours table

Revision ID: fe13af0ca509
Revises: aa07aa9f1456
Create Date: 2025-05-13 11:51:05.134748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe13af0ca509'
down_revision = 'aa07aa9f1456'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('colours')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colours',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('rgb_val', sa.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
